[project]
name = "imgeditor"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.11.8"
pillow = ">=10.2.0,<10.3"
scipy = ">=1.12.0,<1.13"
numpy = ">=1.26.4,<1.27"
matplotlib = ">=3.8.3,<3.9"
tk = ">=8.6.13,<8.7"
opencv = ">=4.9.0,<4.10"
flask = ">=3.0.3,<3.1"

